name = "ks-premium"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KS_LICENSES"
id = "92123e6f49244abb883fae570f389a63"

# Les secrets (STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, RESEND_API_KEY)
# se configurent via : wrangler secret put NOM_DE_LA_VARIABLE
# Ou directement dans le dashboard Cloudflare → Workers → Settings → Variables
